---
title: "Noordzee"
author: "Willem Stolte"
date: "Friday, May 22, 2015"
output: ioslides_presentation
runtime: shiny
---
```{r load_packages, include=FALSE}
require(ggplot2)
require(plyr)
require(pander)
require(shiny)
require(dplyr)
```

## Shiny Presentation

This R Markdown presentation is made interactive using Shiny. The viewers of the presentation can change the assumptions underlying what's presented and see the results immediately. 

To learn more, see [Interactive Documents](http://rmarkdown.rstudio.com/authoring_shiny.html).

## Waar is allemaal gemonsterd?

```{r, echo=F}
load(file = "DATA/MWTL_Noordzee_bewerkt.Rdata")
print(ddply(rws_dat, .(locatie), summarize, startjaar = format(min(datetime), format = "%Y",), eindjaar = format(max(datetime), format = "%Y")), row.names = F)
```

## Slide with Interactive Plot

```{r, echo=FALSE}
inputPanel(selectInput("location", "Location:", selected = "Terschelling 10 km uit de kust", 
                       choices = levels(rws_dat$locatie)),
           selectInput("substance", "Substance:", selected = "opgelost fosfaat", 
                       choices = levels(as.factor(rws_dat$variable))),
           sliderInput("lspan", "Loess span", value = 0.3,
                       min = 0, max = 1, 0.7, step = 0.05, sep = "")
)
renderPlot({width = 0.5
subdf = subset(rws_dat, rws_dat$variable == input$substance &
                 rws_dat$locatie == input$location)
require(ggplot2)
pl <- ggplot(subdf, aes(datetime, waarde))
pl + 
  geom_point(aes(), color = "seagreen4", alpha = 0.5) + 
  geom_smooth(aes(), method='loess', span = input$lspan, size = 1) +
  theme_classic(base_size = 18)
})
```

## Wat gebeurt er met zuurstof? {.smaller}

```{r, echo=FALSE, fig.width=6, fig.height=5}
rws_O2Perc <- filter(rws_dat, waarnemingssoort %in% 
                       c("Percentage zuurstof in % in oppervlaktewater",
                         "Zuurstof in mg/l in oppervlaktewater", 
                         "Temperatuur in oC in oppervlaktewater")
                     &
                       year > 2008
)
plot <- ggplot(data = rws_O2Perc, aes(x = datetime, y = waarde)) + 
  geom_point(aes(color = locatie), size = 1, alpha = 0.7) + 
  geom_smooth(aes(), method='lm', formula = y ~ x+I(cos(2*pi*x/31622400))+I(sin(2*pi*x/31622400))) +
  facet_grid(waarnemingssoort ~ ., scales = "free") +
  guides(color=FALSE)
plot
```


## Conclusies


